<?php

namespace App\Enums;

enum ProjectRole: string
{
    case Executive        = 'executive';
    case SeniorUser       = 'senior_user';
    case SeniorSupplier   = 'senior_supplier';
    case ProjectManager   = 'project_manager';
    case ProjectAssurance = 'project_assurance';
    case ProjectSupport   = 'project_support';
    case ChangeAuthority  = 'change_authority';
    case TeamManager      = 'team_manager';
    case TeamMember       = 'team_member';
    case Observer         = 'observer';

    public function can(string $permission): bool
    {
        return in_array($permission, $this->permissions());
    }

    public function permissions(): array
    {
        return match ($this) {
            self::Executive => [
                'projects:read',
                'stages:read',
                'boundaries:read', 'boundaries:approve-reject',
                'issue-log:read',
                'risk-log:read',
                'change-log:read', 'change-log:approve-major',
                'quality-register:read',
                'lessons-log:read',
                'products:read',
                'plans:read',
                'qa:read',
                'tasks:read',
                'meetings:read',
                'reports:read', 'reports:approve',
                'people:read',
            ],
            self::SeniorUser => [
                'projects:read',
                'stages:read',
                'boundaries:read', 'boundaries:approve-reject',
                'issue-log:read',
                'risk-log:read',
                'change-log:read', 'change-log:approve-major',
                'quality-register:read', 'quality-register:manage',
                'lessons-log:read',
                'products:read',
                'plans:read',
                'qa:read',
                'tasks:read',
                'meetings:read',
                'reports:read', 'reports:approve',
                'people:read',
            ],
            self::SeniorSupplier => [
                'projects:read',
                'stages:read',
                'boundaries:read', 'boundaries:approve-reject',
                'issue-log:read',
                'risk-log:read',
                'change-log:read', 'change-log:approve-major',
                'quality-register:read',
                'lessons-log:read',
                'products:read',
                'plans:read',
                'qa:read',
                'tasks:read',
                'meetings:read',
                'reports:read', 'reports:approve',
                'people:read',
            ],
            self::ProjectManager => [
                'projects:read', 'projects:create', 'projects:update', 'projects:delete',
                'stages:read', 'stages:manage', 'stages:transition',
                'boundaries:read', 'boundaries:manage', 'boundaries:submit',
                'daily-log:read', 'daily-log:manage',
                'issue-log:read', 'issue-log:create', 'issue-log:manage', 'issue-log:escalate',
                'risk-log:read', 'risk-log:create', 'risk-log:manage',
                'change-log:read', 'change-log:create', 'change-log:manage',
                'quality-register:read', 'quality-register:manage',
                'lessons-log:read', 'lessons-log:create', 'lessons-log:manage',
                'products:read', 'products:manage',
                'plans:read', 'plans:manage',
                'qa:read', 'qa:manage',
                'tasks:read', 'tasks:manage',
                'meetings:read', 'meetings:manage',
                'reports:read', 'reports:generate',
                'people:read', 'people:manage',
                'project-team:manage',
            ],
            self::ProjectAssurance => [
                'projects:read',
                'stages:read',
                'boundaries:read',
                'daily-log:read',
                'issue-log:read', 'issue-log:create',
                'risk-log:read', 'risk-log:create',
                'change-log:read',
                'quality-register:read', 'quality-register:manage',
                'lessons-log:read', 'lessons-log:create',
                'products:read', 'products:manage',
                'plans:read',
                'qa:read', 'qa:manage',
                'tasks:read',
                'meetings:read',
                'reports:read',
                'people:read',
            ],
            self::ProjectSupport => [
                'projects:read', 'projects:update',
                'stages:read', 'stages:manage',
                'boundaries:read', 'boundaries:manage',
                'daily-log:read', 'daily-log:manage',
                'issue-log:read', 'issue-log:create', 'issue-log:manage',
                'risk-log:read', 'risk-log:create', 'risk-log:manage',
                'change-log:read', 'change-log:create', 'change-log:manage',
                'quality-register:read', 'quality-register:manage',
                'lessons-log:read', 'lessons-log:create', 'lessons-log:manage',
                'products:read', 'products:manage',
                'plans:read', 'plans:manage',
                'qa:read', 'qa:manage',
                'tasks:read', 'tasks:manage',
                'meetings:read', 'meetings:manage',
                'reports:read', 'reports:generate',
                'people:read', 'people:manage',
                'project-team:manage',
            ],
            self::ChangeAuthority => [
                'projects:read',
                'stages:read',
                'boundaries:read',
                'issue-log:read',
                'risk-log:read',
                'change-log:read', 'change-log:manage', 'change-log:approve-minor',
                'quality-register:read',
                'lessons-log:read',
                'products:read',
                'plans:read',
                'qa:read',
                'tasks:read',
                'meetings:read',
                'reports:read',
                'people:read',
            ],
            self::TeamManager => [
                'projects:read',
                'stages:read',
                'boundaries:read',
                'issue-log:read', 'issue-log:create',
                'risk-log:read', 'risk-log:create',
                'change-log:read', 'change-log:create',
                'quality-register:read',
                'lessons-log:read', 'lessons-log:create',
                'products:read',
                'plans:read',
                'qa:read',
                'tasks:read', 'tasks:manage',
                'meetings:read', 'meetings:manage',
                'reports:read',
                'people:read',
            ],
            self::TeamMember => [
                'projects:read',
                'stages:read',
                'issue-log:read', 'issue-log:create',
                'change-log:read', 'change-log:create',
                'lessons-log:read', 'lessons-log:create',
                'products:read',
                'plans:read',
                'qa:read',
                'tasks:read', 'tasks:update-own',
                'meetings:read',
            ],
            self::Observer => [
                'projects:read',
                'stages:read',
                'boundaries:read',
                'issue-log:read',
                'risk-log:read',
                'change-log:read',
                'quality-register:read',
                'lessons-log:read',
                'products:read',
                'plans:read',
                'qa:read',
                'reports:read',
            ],
        };
    }
}
